services:
    randomail-app:
        image: alpine
        dns:
            - 1.1.1.1
        ports:
            - "127.0.0.1:3000:3000"
        volumes:
            - ./app/randomail-app:/app/randomail-app
            - ./app/config.json:/app/config.json:ro
        command: /app/randomail-app
        working_dir: /app
        restart: unless-stopped
