services:
    randomail-app:
        image: debian:bookworm-slim
        dns:
            - 1.1.1.1
        ports:
            - "127.0.0.1:3000:3000"
        volumes:
            - ./randomail-app:/randomail-app
            - ./config.json:/config.json:ro
        command: /randomail-app
        restart: unless-stopped
