services:
    randomail-app:
        image: debian:bookworm-slim
        ports:
            - "3000:3000"
        volumes:
            - ./randomail-app:/randomail-app
            - ./config.json:/config.json:ro
        command: /randomail-app
        restart: unless-stopped
