[package]
name = "randomail-api"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
dirs.workspace = true
log.workspace = true
minreq.workspace = true
serde.workspace = true
serde_json.workspace = true
tabled.workspace = true

[lints]
workspace = true
