[package]
name = "randomail"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
env_logger.workspace = true
log.workspace = true
randomail-api = { path = "../randomail-api" }
tabled.workspace = true

[lints]
workspace = true
